version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ubuntu/PizzaDeliveryService
hooks:
  ApplicationStop:
    - location: remove_app.sh
      timeout: 30
  ApplicationStart:
    - location: install_app.sh
      timeout: 300